Update to JSX3
ahrefs/bs-reactstrap pull request #32
Opened 2019-04-27 10:01 UTC by Anahkiasen

This makes the components usable in a codebase using the [v3 implementation of JSX](https://reasonml.github.io/reason-react/blog/2019/04/10/react-hooks) following the new [documentation](https://reasonml.github.io/reason-react/docs/en/components#interop)

2019-04-27 10:34 UTC, Anahkiasen commented
Seems I need to add the `~children` prop to most of these to make it fully work

2019-05-19 12:59 UTC, tepafoo commented
+1

Updating to JSX3 would be very useful!

Anything we can do to help with the PR getting merged into master and published to npm? I'm happy to help.

2019-05-20 09:00 UTC, rusty-key requested changes
Sorry for the late response, I somehow didn't receive notifications for this repo.

Yeah, to make it work, we need to deal with `children` first. 

Also, it would be nice to keep compatibility with jsx2 for some time. We can do it by adding a wrapper to each file and transform children to array: 

```
[@bs.module "reactstrap"] [@react.component]
external make:
  (~tag: 'a=?, ~fluid: bool=?, ~className: string=?, ~cssModule: 'b=?, ~children, unit) => React.element =
  "Container";

module Jsx2 = {
  let component = ReasonReact.statelessComponent(__MODULE__);

  let make = (~tag=?, ~fluid=?, ~className=?, ~cssModule=?, children) => {
    let children = React.array(children);
    ReasonReactCompat.wrapReactForReasonReact(
      make,
      makeProps(~tag?, ~fluid?, ~className?, ~cssModule?, ~children, ()),
      children,
    );
  };
}
```

What do you think? Can you do that?

2019-05-20 09:00 UTC, rusty-key commented on src/BsReactstrap__Alert.re
> +  "Alert";
Please add newlines at the end of the files too. 
If you are using vscode, you can add `"files.insertFinalNewline": true,` to your config

2019-05-20 16:39 UTC, rusty-key commented
I updated your PR:
— ran refmt on everything
— added children (blindly, to all component, we can remove them later)
— added jsx2 wrappers (generated with this script: https://gist.github.com/rusty-key/20d228a416fc70d31a71056bb03c9853)

2019-05-20 17:00 UTC, liubko commented
@rusty-key looks good to me

2019-05-20 17:34 UTC, rusty-key commented
ok, let's try it

2019-05-20 17:34 UTC, merged

2019-05-21 08:28 UTC, Anahkiasen commented
Nice, very cool!

2019-05-21 08:34 UTC, liubko commented
published v1.0.3

2019-05-21 22:30 UTC, tepafoo commented
Thank you!

2019-09-17 03:52 UTC, nirvdrum commented on src/BsReactstrap__Input.re
> +        ~_type=?,
FYI, this is a regression from the path taken as of #19.